"""
maintenance.py — Routes de maintenance OmniBank.
Fournit des endpoints pour diagnostiquer et corriger les incohérences de données.
"""
from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from sqlalchemy import text
from typing import List
from app.database import get_db

router = APIRouter(prefix="/api/maintenance", tags=["Maintenance"])


def _find_mismatch_rows(db: Session):
    """Return transactions with type=expense_var but having recurrence."""
    result = db.execute(text("""
        SELECT t.id, t.description, t.amount, t.type, t.date_operation, t.category, t.recurrence_id, t.is_monthly
        FROM transactions t
        LEFT JOIN recurrence_templates rt ON t.recurrence_id = rt.id
        WHERE t.type = 'expense_var'
          AND (t.is_monthly = 1 OR t.recurrence_id IS NOT NULL)
          AND (rt.id IS NULL OR rt.type = 'expense_fixed')
        ORDER BY t.date_operation DESC
    """))
    return [dict(r._mapping) for r in result]


def _find_affected_categories(db: Session, tx_ids: list[int]) -> list[str]:
    if not tx_ids:
        return []
    placeholders = ','.join(str(i) for i in tx_ids)
    result = db.execute(text(f"""
        SELECT DISTINCT category FROM transactions
        WHERE id IN ({placeholders})
          AND category IS NOT NULL AND category != ''
    """))
    return [r[0] for r in result]


def _cat_has_other_expense_var(db: Session, cat_name: str, exclude_ids: list[int]) -> bool:
    placeholders = ','.join(str(i) for i in exclude_ids) if exclude_ids else '0'
    result = db.execute(text(f"""
        SELECT COUNT(*) FROM transactions
        WHERE type = 'expense_var'
          AND category = :cat
          AND id NOT IN ({placeholders})
    """), {'cat': cat_name})
    return result.scalar() > 0


@router.get("/fix_type_mismatch/preview")
def preview_fix(db: Session = Depends(get_db)):
    """
    Retourne la liste des transactions mal typées (expense_var avec récurrence)
    ainsi que les catégories concernées et si elles sont partagées avec d'autres
    transactions expense_var légitimes.
    """
    rows = _find_mismatch_rows(db)
    tx_ids = [r['id'] for r in rows]
    affected_cats = _find_affected_categories(db, tx_ids)

    cat_info = []
    for cat in affected_cats:
        shared = _cat_has_other_expense_var(db, cat, tx_ids)
        cat_info.append({
            "name": cat,
            "shared": shared,  # True = also used in legit expense_var ops → user choice needed
            "default_action": "keep" if shared else "move"
        })

    return {
        "count": len(rows),
        "sample": rows[:10],
        "affected_categories": cat_info
    }


@router.post("/fix_type_mismatch/apply")
def apply_fix(
    db: Session = Depends(get_db),
    cat_moves: str = Query(default="", description="Comma-separated category names to MOVE to expense_fixed")
):
    """
    Applique la correction:
    - Met à jour toutes les transactions expense_var avec récurrence → expense_fixed
    - Pour les catégories listées dans cat_moves : les déplace vers expense_fixed
    - Pour les autres catégories affectées non listées : les laisse en expense_var
    """
    rows = _find_mismatch_rows(db)
    tx_ids = [r['id'] for r in rows]

    if not tx_ids:
        return {"tx_fixed": 0, "cat_fixed": 0, "message": "Aucune correction nécessaire."}

    # Fix transactions
    placeholders = ','.join(str(i) for i in tx_ids)
    db.execute(text(f"""
        UPDATE transactions SET type = 'expense_fixed'
        WHERE id IN ({placeholders})
    """))
    tx_fixed = len(tx_ids)

    # Fix categories
    to_move = [c.strip() for c in cat_moves.split(',') if c.strip()] if cat_moves else []
    cat_fixed = 0
    affected_cats = _find_affected_categories(db, tx_ids)
    for cat in affected_cats:
        shared = _cat_has_other_expense_var(db, cat, tx_ids)
        if not shared or cat in to_move:
            result = db.execute(text("""
                UPDATE categories SET type = 'expense_fixed'
                WHERE name = :name AND type = 'expense_var'
            """), {'name': cat})
            if result.rowcount > 0:
                cat_fixed += 1

    db.commit()
    return {
        "tx_fixed": tx_fixed,
        "cat_fixed": cat_fixed,
        "message": f"Migration terminée : {tx_fixed} transactions, {cat_fixed} catégories."
    }


# ---------------------------------------------------------------------------
# Orphan recurrence cleanup — detect & remove recurrence-generated
# transactions that belong to years where the template was never confirmed
# (i.e. no reconciled transaction exists for that template in that year).
# ---------------------------------------------------------------------------

def _find_orphan_recurrence_transactions(db: Session):
    """
    Returns unreconciled transactions linked to a recurrence template
    for a year where that template has ZERO reconciled transactions.
    This detects transactions generated by mistake for years where the
    recurrence was not truly active.
    """
    # Step 1: find all (recurrence_id, year) pairs that have at least one reconciled tx
    result_confirmed = db.execute(text("""
        SELECT recurrence_id, CAST(strftime('%Y', date_operation) AS INTEGER) AS yr
        FROM transactions
        WHERE recurrence_id IS NOT NULL
          AND reconciliation_date IS NOT NULL
        GROUP BY recurrence_id, yr
    """))
    confirmed_pairs = set()
    for row in result_confirmed:
        confirmed_pairs.add((row[0], row[1]))

    # Step 2: find all unreconciled transactions linked to a recurrence
    result_candidates = db.execute(text("""
        SELECT t.id, t.description, t.amount, t.date_operation, t.type, t.category,
               t.recurrence_id, rt.description AS tpl_description, rt.is_closed
        FROM transactions t
        JOIN recurrence_templates rt ON t.recurrence_id = rt.id
        WHERE t.recurrence_id IS NOT NULL
          AND t.reconciliation_date IS NULL
        ORDER BY t.recurrence_id, t.date_operation
    """))

    orphans = []
    for row in result_candidates:
        row_dict = dict(row._mapping)
        tx_year = int(str(row_dict['date_operation'])[:4])
        rec_id = row_dict['recurrence_id']
        is_closed = bool(row_dict['is_closed'])

        # If the template is closed AND this (template, year) has NO confirmed transactions → orphan candidate
        if is_closed and (rec_id, tx_year) not in confirmed_pairs:
            row_dict['year'] = tx_year
            orphans.append(row_dict)

    return orphans



@router.get("/orphan_recurrences/preview")
def preview_orphan_recurrences(db: Session = Depends(get_db)):
    """
    Returns unreconciled transactions that are likely orphans:
    they belong to a recurrence template that has no reconciled
    transactions in the same year.
    """
    orphans = _find_orphan_recurrence_transactions(db)

    # Group by template for readability
    grouped = {}
    for o in orphans:
        key = o['recurrence_id']
        if key not in grouped:
            grouped[key] = {
                'template_id': key,
                'template_description': o['tpl_description'],
                'is_closed': o['is_closed'],
                'transactions': []
            }
        grouped[key]['transactions'].append({
            'id': o['id'],
            'description': o['description'],
            'amount': o['amount'],
            'date_operation': str(o['date_operation']),
            'category': o['category'],
            'type': o['type'],
            'year': o['year']
        })

    return {
        'count': len(orphans),
        'groups': list(grouped.values())
    }


@router.post("/orphan_recurrences/cleanup")
def cleanup_orphan_recurrences(
    tx_ids: List[int],
    db: Session = Depends(get_db)
):
    """
    Deletes the specified transaction IDs, but ONLY if they are
    unreconciled and linked to a recurrence template.
    This is a safe guard: reconciled transactions cannot be deleted.
    """
    if not tx_ids:
        return {"deleted": 0}

    deleted = 0
    for tx_id in tx_ids:
        result = db.execute(text("""
            DELETE FROM transactions
            WHERE id = :id
              AND recurrence_id IS NOT NULL
              AND reconciliation_date IS NULL
        """), {'id': tx_id})
        deleted += result.rowcount

    db.commit()
    return {"deleted": deleted}

