from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List, Optional
from datetime import date
from dateutil.relativedelta import relativedelta

import calendar

from app.database import get_db
from app.models import RecurrenceTemplate, Transaction, Category
from app.schemas.api_schemas import RecurrenceTemplateCreate, RecurrenceTemplateOut, PropagateRequest, WizardGenerateRequest

router = APIRouter(prefix="/api/recurrences", tags=["recurrences"])

def _upgrade_category_if_needed(category_name: str, tpl_type: str, db: Session):
    if not category_name or tpl_type != "expense_fixed":
        return
    db_cat = db.query(Category).filter(Category.name == category_name).first()
    if db_cat and db_cat.type == "expense_var":
        db_cat.type = "expense_fixed"

@router.get("/", response_model=List[RecurrenceTemplateOut])
def get_templates(include_closed: bool = False, db: Session = Depends(get_db)):
    if include_closed:
        return db.query(RecurrenceTemplate).all()
    return db.query(RecurrenceTemplate).filter(
        (RecurrenceTemplate.is_closed == False) | (RecurrenceTemplate.is_closed == None)
    ).all()

@router.post("/", response_model=RecurrenceTemplateOut)
def create_template(tpl: RecurrenceTemplateCreate, db: Session = Depends(get_db)):
    db_tpl = RecurrenceTemplate(**tpl.dict())
    db.add(db_tpl)
    _upgrade_category_if_needed(db_tpl.category, db_tpl.type, db)
    db.commit()
    db.refresh(db_tpl)
    return db_tpl

@router.put("/{tpl_id}", response_model=RecurrenceTemplateOut)
def update_template(tpl_id: int, tpl_update: RecurrenceTemplateCreate, db: Session = Depends(get_db)):
    db_tpl = db.query(RecurrenceTemplate).filter(RecurrenceTemplate.id == tpl_id).first()
    if not db_tpl:
        raise HTTPException(status_code=404, detail="Template not found")
    update_data = tpl_update.dict(exclude_unset=True)
    for key, value in update_data.items():
        if hasattr(db_tpl, key):
            setattr(db_tpl, key, value)
    _upgrade_category_if_needed(db_tpl.category, db_tpl.type, db)
    db.commit()
    db.refresh(db_tpl)
    return db_tpl

@router.delete("/{tpl_id}")
def delete_template(tpl_id: int, db: Session = Depends(get_db)):
    db_tpl = db.query(RecurrenceTemplate).filter(RecurrenceTemplate.id == tpl_id).first()
    if not db_tpl:
        raise HTTPException(status_code=404, detail="Template not found")
        
    # Delete unreconciled transactions generated by this template
    db.query(Transaction).filter(
        Transaction.recurrence_id == tpl_id,
        Transaction.reconciliation_date == None
    ).delete()
    
    db.delete(db_tpl)
    db.commit()
    return {"ok": True}

@router.post("/{tpl_id}/propagate")
def propagate_recurrence(tpl_id: int, req: PropagateRequest, db: Session = Depends(get_db)):
    tpl = db.query(RecurrenceTemplate).filter(RecurrenceTemplate.id == tpl_id).first()
    if not tpl:
        raise HTTPException(status_code=404, detail="Template not found")
        
    tx = db.query(Transaction).filter(Transaction.id == req.transaction_id).first()
    if not tx:
        raise HTTPException(status_code=404, detail="Origin transaction not found")
        
    old_date = tx.date_operation
    
    # Update template
    tpl.amount = req.new_amount
    tpl.day_of_month = req.new_date.day
    
    # Update origin transaction exactly
    tx.date_operation = req.new_date
    tx.amount = req.new_amount
    
    # Find all unreconciled transactions for this template from old_date onwards (excluding origin)
    txs = db.query(Transaction).filter(
        Transaction.recurrence_id == tpl_id,
        Transaction.date_operation > old_date,
        Transaction.reconciliation_date == None
    ).all()
    
    updated_count = 1
    for t in txs:
        t.amount = req.new_amount
        
        # update day of month safely
        last_day = calendar.monthrange(t.date_operation.year, t.date_operation.month)[1]
        safe_day = min(req.new_date.day, last_day)
        t.date_operation = t.date_operation.replace(day=safe_day)
        updated_count += 1
        
    # Generate missing transactions for the rest of the year being edited
    end_of_year = date(req.new_date.year, 12, 31)
    current_date = req.new_date
    if tpl.frequency == "Monthly":
        current_date += relativedelta(months=1)
    elif tpl.frequency == "Yearly":
        current_date += relativedelta(years=1)
    elif tpl.frequency in ("Bi-Weekly", "Bi-Monthly"):
        current_date += relativedelta(weeks=2)
 
    existing_count = 0
    if tpl.max_occurrences:
        existing_count = db.query(Transaction).filter(
            Transaction.recurrence_id == tpl.id
        ).count()
    tpl_generated = 0
    
    while True:
        if tpl.max_occurrences and (existing_count + tpl_generated) >= tpl.max_occurrences:
            break
        if not tpl.max_occurrences and current_date > end_of_year:
            break
            
        exists = db.query(Transaction).filter(
            Transaction.description == tpl.description,
            Transaction.date_operation == current_date
        ).first()
    
        if not exists:
            new_tx = Transaction(
                date_saisie=date.today(),
                date_operation=current_date,
                description=tpl.description,
                amount=tpl.amount,
                type=tpl.type,
                category=tpl.category,
                is_monthly=(tpl.frequency == "Monthly"),
                is_yearly=(tpl.frequency == "Yearly"),
                from_account_id=tpl.from_account_id,
                to_account_id=tpl.to_account_id,
                recurrence_id=tpl.id
            )
            db.add(new_tx)
            updated_count += 1
            tpl_generated += 1
            
        if tpl.frequency == "Monthly":
            current_date += relativedelta(months=1)
        elif tpl.frequency == "Yearly":
            current_date += relativedelta(years=1)
        elif tpl.frequency in ("Bi-Weekly", "Bi-Monthly"):
            current_date += relativedelta(weeks=2)
        else:
            break
            
    db.commit()
    return {"updated": updated_count}

@router.post("/generate_to_end_of_year")
def generate_recurrences(template_id: Optional[int] = None, db: Session = Depends(get_db)):
    """Generate instances for active templates until the end of the current year.
    
    If template_id is specified, only that template is processed.
    
    IMPORTANT: Only generates for templates that already have at least one transaction
    linked via recurrence_id. This prevents orphaned/legacy templates from flooding
    the database with unwanted past occurrences.
    """
    query = db.query(RecurrenceTemplate).filter(
        (RecurrenceTemplate.is_closed == False) | (RecurrenceTemplate.is_closed == None)
    )
    if template_id is not None:
        query = query.filter(RecurrenceTemplate.id == template_id)
        
    templates = query.all()
    today = date.today()
    end_of_year = date(today.year, 12, 31)
    
    generated_count = 0
    
    for tpl in templates:
        # Anchor on the latest existing transaction belonging to this template
        latest_tx = db.query(Transaction).filter(
            Transaction.recurrence_id == tpl.id
        ).order_by(Transaction.date_operation.desc()).first()
        
        # CRITICAL: If no transaction is linked to this template, skip it entirely.
        # This prevents legacy templates (created before recurrence_id tracking) from
        # generating hundreds of unwanted past transactions.
        if not latest_tx:
            continue
        
        current_date = latest_tx.date_operation
        # Advance by one interval before generating new occurrences
        if tpl.frequency == "Monthly":
            current_date += relativedelta(months=1)
        elif tpl.frequency == "Yearly":
            current_date += relativedelta(years=1)
        elif tpl.frequency in ("Bi-Weekly", "Bi-Monthly"):
            current_date += relativedelta(weeks=2)
        else:
            continue
        
        # GUARD: Never generate transactions in the past.
        # Fast-forward until current_date is at least in the current month.
        first_of_current_month = date(today.year, today.month, 1)
        while current_date < first_of_current_month:
            if tpl.frequency == "Monthly":
                current_date += relativedelta(months=1)
            elif tpl.frequency == "Yearly":
                current_date += relativedelta(years=1)
            elif tpl.frequency in ("Bi-Weekly", "Bi-Monthly"):
                current_date += relativedelta(weeks=2)
            else:
                break
        
        # Hard ceiling: never generate past end of year
        if current_date > end_of_year:
            continue
            
        existing_count = db.query(Transaction).filter(
            Transaction.recurrence_id == tpl.id
        ).count()
        
        tpl_generated = 0
            
        while current_date <= end_of_year:
            # Stop if max occurrences reached
            if tpl.max_occurrences and (existing_count + tpl_generated) >= tpl.max_occurrences:
                break
                
            # Duplicate check: two-layer defense
            # 1. Check by recurrence_id (for properly linked transactions)
            # 2. Check by description (for legacy/manually-entered transactions without recurrence_id)
            # IMPORTANT: SQLite stores dates as TEXT, so we use strftime() not extract().
            from sqlalchemy import func, or_
            year_month = current_date.strftime('%Y-%m')
            already_exists = db.query(Transaction).filter(
                func.strftime('%Y-%m', Transaction.date_operation) == year_month,
                or_(
                    Transaction.recurrence_id == tpl.id,
                    Transaction.description == tpl.description
                )
            ).first()
            
            if not already_exists:
                new_tx = Transaction(
                    date_saisie=today,
                    date_operation=current_date,
                    description=tpl.description,
                    amount=tpl.amount,
                    type=tpl.type,
                    category=tpl.category,
                    is_monthly=(tpl.frequency == "Monthly"),
                    is_yearly=(tpl.frequency == "Yearly"),
                    from_account_id=tpl.from_account_id,
                    to_account_id=tpl.to_account_id,
                    recurrence_id=tpl.id
                )
                db.add(new_tx)
                generated_count += 1
                tpl_generated += 1
                
            if tpl.frequency == "Monthly":
                current_date += relativedelta(months=1)
            elif tpl.frequency == "Yearly":
                current_date += relativedelta(years=1)
            elif tpl.frequency in ("Bi-Weekly", "Bi-Monthly"):
                current_date += relativedelta(weeks=2)
            else:
                break # safeguard
                
    db.commit()
    return {"generated_instances": generated_count}

@router.post("/wizard_generate")
def wizard_generate(req: WizardGenerateRequest, db: Session = Depends(get_db)):
    """Apply wizard updates, add new templates, and generate for the target year."""
    # 1. Update existing templates
    for update in req.updates:
        tpl = db.query(RecurrenceTemplate).filter(RecurrenceTemplate.id == update.id).first()
        if tpl:
            if not update.renew:
                tpl.is_closed = True
            else:
                if update.amount is not None:
                    tpl.amount = update.amount
                if update.day_of_month is not None:
                    tpl.day_of_month = update.day_of_month
                if update.category is not None:
                    tpl.category = update.category
                if update.frequency is not None:
                    tpl.frequency = update.frequency

    # 2. Add new templates
    for new_tpl in req.new_templates:
        db_tpl = RecurrenceTemplate(**new_tpl.dict())
        db.add(db_tpl)
        
    db.commit()

    # 3. Generate instances for target year
    generated_count = 0
    if req.generate_instances:
        templates = db.query(RecurrenceTemplate).filter(
            (RecurrenceTemplate.is_closed == False) | (RecurrenceTemplate.is_closed == None)
        ).all()
        
        today = date.today()
        start_of_year = date(req.target_year, 1, 1)
        end_of_year = date(req.target_year, 12, 31)
        
        for tpl in templates:
            # Start date for generating
            current_date = date(req.target_year, 1, tpl.day_of_month or 1)
            
            # Adjust if frequency is Yearly and month is specified
            if tpl.frequency == "Yearly":
                current_date = date(req.target_year, tpl.month_of_year or 1, tpl.day_of_month or 1)
                
            existing_count = 0
            if tpl.max_occurrences:
                existing_count = db.query(Transaction).filter(
                    Transaction.recurrence_id == tpl.id
                ).count()
            tpl_generated = 0
                
            while True:
                if tpl.max_occurrences and (existing_count + tpl_generated) >= tpl.max_occurrences:
                    break
                if not tpl.max_occurrences and current_date > end_of_year:
                    break
                    
                from sqlalchemy import func
                if tpl.frequency == "Monthly":
                    exists = db.query(Transaction).filter(
                        Transaction.description == tpl.description,
                        func.strftime('%Y-%m', Transaction.date_operation) == current_date.strftime('%Y-%m')
                    ).first()
                elif tpl.frequency == "Yearly":
                    exists = db.query(Transaction).filter(
                        Transaction.description == tpl.description,
                        func.strftime('%Y', Transaction.date_operation) == current_date.strftime('%Y')
                    ).first()
                else:
                    exists = db.query(Transaction).filter(
                        Transaction.description == tpl.description,
                        Transaction.date_operation == current_date
                    ).first()
                
                if not exists and current_date >= start_of_year:
                    new_tx = Transaction(
                        date_saisie=today,
                        date_operation=current_date,
                        description=tpl.description,
                        amount=tpl.amount,
                        type=tpl.type,
                        category=tpl.category,
                        is_monthly=(tpl.frequency == "Monthly"),
                        is_yearly=(tpl.frequency == "Yearly"),
                        from_account_id=tpl.from_account_id,
                        to_account_id=tpl.to_account_id,
                        recurrence_id=tpl.id
                    )
                    db.add(new_tx)
                    generated_count += 1
                    tpl_generated += 1
                    
                if tpl.frequency == "Monthly":
                    current_date += relativedelta(months=1)
                elif tpl.frequency == "Yearly":
                    current_date += relativedelta(years=1)
                elif tpl.frequency in ("Bi-Weekly", "Bi-Monthly"):
                    current_date += relativedelta(weeks=2)
                else:
                    break
                    
    db.commit()
    return {"generated_instances": generated_count}


from pydantic import BaseModel
from typing import Optional

class RecurrenceCategoryUpdate(BaseModel):
    category: Optional[str] = None

@router.patch("/{tpl_id}/category", response_model=RecurrenceTemplateOut)
def update_recurrence_category(tpl_id: int, req: RecurrenceCategoryUpdate, db: Session = Depends(get_db)):
    db_tpl = db.query(RecurrenceTemplate).filter(RecurrenceTemplate.id == tpl_id).first()
    if not db_tpl:
        raise HTTPException(status_code=404, detail="Template not found")
        
    db_tpl.category = req.category
    
    # Cascade to unreconciled transactions of this template
    db.query(Transaction).filter(
        Transaction.recurrence_id == tpl_id,
        Transaction.reconciliation_date == None
    ).update({"category": req.category}, synchronize_session=False)
    
    db.commit()
    db.refresh(db_tpl)
    return db_tpl


