from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
from datetime import date
from dateutil.relativedelta import relativedelta

import calendar

from app.database import get_db
from app.models import RecurrenceTemplate, Transaction
from app.schemas.api_schemas import RecurrenceTemplateCreate, RecurrenceTemplateOut, PropagateRequest

router = APIRouter(prefix="/api/recurrences", tags=["recurrences"])

@router.get("/", response_model=List[RecurrenceTemplateOut])
def get_templates(db: Session = Depends(get_db)):
    return db.query(RecurrenceTemplate).all()

@router.post("/", response_model=RecurrenceTemplateOut)
def create_template(tpl: RecurrenceTemplateCreate, db: Session = Depends(get_db)):
    db_tpl = RecurrenceTemplate(**tpl.dict())
    db.add(db_tpl)
    db.commit()
    db.refresh(db_tpl)
    return db_tpl

@router.delete("/{tpl_id}")
def delete_template(tpl_id: int, db: Session = Depends(get_db)):
    db_tpl = db.query(RecurrenceTemplate).filter(RecurrenceTemplate.id == tpl_id).first()
    if not db_tpl:
        raise HTTPException(status_code=404, detail="Template not found")
        
    # Delete unreconciled transactions generated by this template
    db.query(Transaction).filter(
        Transaction.recurrence_id == tpl_id,
        Transaction.reconciliation_date == None
    ).delete()
    
    db.delete(db_tpl)
    db.commit()
    return {"ok": True}

@router.post("/{tpl_id}/propagate")
def propagate_recurrence(tpl_id: int, req: PropagateRequest, db: Session = Depends(get_db)):
    tpl = db.query(RecurrenceTemplate).filter(RecurrenceTemplate.id == tpl_id).first()
    if not tpl:
        raise HTTPException(status_code=404, detail="Template not found")
        
    tx = db.query(Transaction).filter(Transaction.id == req.transaction_id).first()
    if not tx:
        raise HTTPException(status_code=404, detail="Origin transaction not found")
        
    old_date = tx.date_operation
    
    # Update template
    tpl.amount = req.new_amount
    tpl.day_of_month = req.new_date.day
    
    # Update origin transaction exactly
    tx.date_operation = req.new_date
    tx.amount = req.new_amount
    
    # Find all unreconciled transactions for this template from old_date onwards (excluding origin)
    txs = db.query(Transaction).filter(
        Transaction.recurrence_id == tpl_id,
        Transaction.date_operation > old_date,
        Transaction.reconciliation_date == None
    ).all()
    
    updated_count = 1
    for t in txs:
        t.amount = req.new_amount
        
        # update day of month safely
        last_day = calendar.monthrange(t.date_operation.year, t.date_operation.month)[1]
        safe_day = min(req.new_date.day, last_day)
        t.date_operation = t.date_operation.replace(day=safe_day)
        updated_count += 1
        
    # Generate missing transactions for the rest of the year being edited
    end_of_year = date(req.new_date.year, 12, 31)
    current_date = req.new_date
    if tpl.frequency == "Monthly":
        current_date += relativedelta(months=1)
    elif tpl.frequency == "Yearly":
        current_date += relativedelta(years=1)
    elif tpl.frequency == "Bi-Weekly":
        current_date += relativedelta(weeks=2)
        
    while current_date <= end_of_year:
        exists = db.query(Transaction).filter(
            Transaction.description == tpl.description,
            Transaction.date_operation == current_date
        ).first()
        
        if not exists:
            new_tx = Transaction(
                date_saisie=date.today(),
                date_operation=current_date,
                description=tpl.description,
                amount=tpl.amount,
                type=tpl.type,
                category=tpl.category,
                is_monthly=(tpl.frequency == "Monthly"),
                is_yearly=(tpl.frequency == "Yearly"),
                from_account_id=tpl.from_account_id,
                to_account_id=tpl.to_account_id,
                recurrence_id=tpl.id
            )
            db.add(new_tx)
            updated_count += 1
            
        if tpl.frequency == "Monthly":
            current_date += relativedelta(months=1)
        elif tpl.frequency == "Yearly":
            current_date += relativedelta(years=1)
        elif tpl.frequency == "Bi-Weekly":
            current_date += relativedelta(weeks=2)
        else:
            break
            
    db.commit()
    return {"updated": updated_count}

@router.post("/generate_to_end_of_year")
def generate_recurrences(db: Session = Depends(get_db)):
    """Generate instances for all active templates until the end of the current year."""
    templates = db.query(RecurrenceTemplate).all()
    today = date.today()
    end_of_year = date(today.year, 12, 31)
    
    generated_count = 0
    
    for tpl in templates:
        current_date = date(today.year, today.month, tpl.day_of_month or 1)
        if current_date < today:
            if tpl.frequency == "Bi-Weekly":
                while current_date < today:
                    current_date += relativedelta(weeks=2)
            elif tpl.frequency == "Yearly":
                current_date += relativedelta(years=1)
            else:
                current_date += relativedelta(months=1)
            
        while current_date <= end_of_year:
            # Check if this exact recurrent transaction already exists to avoid duplicates
            # A simple heuristic: same description and same date
            exists = db.query(Transaction).filter(
                Transaction.description == tpl.description,
                Transaction.date_operation == current_date
            ).first()
            
            if not exists:
                new_tx = Transaction(
                    date_saisie=today,
                    date_operation=current_date,
                    description=tpl.description,
                    amount=tpl.amount,
                    type=tpl.type,
                    category=tpl.category,
                    is_monthly=(tpl.frequency == "Monthly"),
                    is_yearly=(tpl.frequency == "Yearly"),
                    from_account_id=tpl.from_account_id,
                    to_account_id=tpl.to_account_id,
                    recurrence_id=tpl.id
                )
                db.add(new_tx)
                generated_count += 1
                
            if tpl.frequency == "Monthly":
                current_date += relativedelta(months=1)
            elif tpl.frequency == "Yearly":
                current_date += relativedelta(years=1)
            elif tpl.frequency == "Bi-Weekly":
                current_date += relativedelta(weeks=2)
            else:
                break # safeguard
                
    db.commit()
    return {"generated_instances": generated_count}
